name: Progress
on:
  push:
    paths:
      - 'python/**.py'
      - 'scripts/update_progress.py'
  workflow_dispatch:
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.x' }
      - run: python scripts/update_progress.py
      - name: Commit updated README
        run: |
          git config user.name "progress-bot"
          git config user.email "actions@users.noreply.github.com"
          git add README.md
          git commit -m "chore: update progress" || echo "no changes"
          git push
